const STEPS_ADD_WORD_SENTENCE = {
	STEP_0: 0,
	STEP_1: 1,
	STEP_2: 2,
	STEP_3: 3,
};

const RES_DATA = 0;

const LIMIT_TEXT_OF_PAGE = 5;

export { STEPS_ADD_WORD_SENTENCE, RES_DATA, LIMIT_TEXT_OF_PAGE };
